name: run Main.py

on:
  schedule:
    # At 16:00 on every 26th day-of-month. (crontab.guru/#0_16_*/26_*_*)
    - cron: '*/21 * * * *'

jobs:
  runs:
    runs-on: ubuntu-latest
    steps:
      - name: set up python
        uses: actions/checkout@main
        with:
          python-version: '3.9'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute Main.py
        run: python Main.py
